name: lume_ui
description: "A collection of beautiful and reusable Flutter UI components including buttons, dialogs, media players, carousels, danmaku pool, gaussian blur effects, and more."
version: 1.0.1
homepage: https://github.com/BeiChuanc/flutter_ui_components.git

environment:
  sdk: ^3.10.1
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3     # 屏幕适配
  bot_toast: ^4.1.3              # 全局弹窗
  smooth_page_indicator: ^1.2.1  # 指示器
  video_player: ^2.9.5           # 视频播放
  video_thumbnail: ^0.5.6        # 视频缩略图
  path_provider: ^2.0.14         # 路径提供
  webview_flutter: ^4.11.0       # 网页视图
  crypto: ^3.0.6                 # Crypto加密

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

